### PR TITLE
Ubuntu transition

### PR DESCRIPTION
**Pull request by brosenberg42**
**Issues:**
- https://github.com/openmpf/openmpf/issues/1374
- https://github.com/openmpf/openmpf/issues/1105

**Related PRs:**
- https://github.com/openmpf/openmpf/pull/1447
- https://github.com/openmpf/openmpf-docker/pull/157
- https://github.com/openmpf/openmpf-components/pull/287
- https://github.com/openmpf/openmpf-contrib-components/pull/76
- https://github.com/openmpf/openmpf-cpp-component-sdk/pull/108
- https://github.com/openmpf/openmpf-java-component-sdk/pull/56

---
This change is [Reviewable](https://reviewable.io/reviews/openmpf/openmpf-docker/157)

### CODE REVIEW

**Comment by jrobble** [comment]
___
*[activemq/Dockerfile, line 43 at r1](https://reviewable.io/reviews/openmpf/openmpf-docker/157#-MspjgPVAHhMaNS00GT3:-MspjgPVAHhMaNS00GT4:b-kej8x4) ([raw file](https://github.com/openmpf/openmpf-docker/blob/a5b50cfe23a6b4c6ce525033a05a7ed0f9954660/activemq/Dockerfile#L43)):*
> ```Dockerfile
> RUN wget -O- https://archive.apache.org/dist/activemq/5.16.3/apache-activemq-5.16.3-bin.tar.gz \
>         | tar --extract --gzip --directory /opt; \
>     ln --symbolic /opt/apache-activemq-5.16.3 /opt/activemq; \
> ```

Dropping a note here that we need to either update to ActiveMQ 5.17.0 to address Trivy scan issues, or get sign-off by the end users.

**Review by jrobble — CHANGES_REQUESTED** [review]
> Reviewed 17 of 17 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/openmpf/openmpf-docker/157)* status: all files reviewed, 9 unresolved discussions (waiting on @brosenberg42)

___
*[docker-compose.core.yml, line 46 at r1](https://reviewable.io/reviews/openmpf/openmpf-docker/157#-MuNba4T7yFWFaRw86T3:-MuNba4T7yFWFaRw86T4:bphgc05) ([raw file](https://github.com/openmpf/openmpf-docker/blob/c6f1eccc1eeaddb14dcb3c85f3e10e2dc86ebd32/docker-compose.core.yml#L46)):*
> ```YAML
>     image: ${REGISTRY}openmpf_activemq:${TAG}
>     build: activemq
>     init: true
> ```

Why add this?
___
*[Jenkinsfile, line 428 at r1](https://reviewable.io/reviews/openmpf/openmpf-docker/157#-MuNORQJBnXjc5XrvGeb:-MuNORQKBjj-MJ1r6ZvJ:b-8odax) ([raw file](https://github.com/openmpf/openmpf-docker/blob/c6f1eccc1eeaddb14dcb3c85f3e10e2dc86ebd32/Jenkinsfile#L428)):*
> ```Groovy
>                 def service = composeYaml.services[serviceName]
>                 if (!service.build || serviceName == 'kibana') {
>                     echo "Not scanning $service.image since we didn't build it"
> ```

I think we should scan all of the images, including those we didn't build (or at least provide an option to enable that). That way we can know of all of the issues before they do scans on the production side. For example, I don't want ActiveMQ issues like the log4j 1 ones to come as a surprise.
___
*[Jenkinsfile, line 441 at r1](https://reviewable.io/reviews/openmpf/openmpf-docker/157#-MuNSf-z0_RKR7E-AGbx:-MuNSf-z0_RKR7E-AGby:b95j1qw) ([raw file](https://github.com/openmpf/openmpf-docker/blob/c6f1eccc1eeaddb14dcb3c85f3e10e2dc86ebd32/Jenkinsfile#L441)):*
I think we should alter the status of the job to reflect these findings. How about we mark the build as `UNSTABLE`, as shown [here](https://stackoverflow.com/a/43894382/1424791)?

From the Jenkins API for `UNSTABLE`:

> The build had some errors but they were not fatal. For example, some tests failed.

If a user is actively deciding to enable Trivy scans, I think they would want the job status to reflect the result of the scans.

I could see how changing the status might be an annoyance if the scan is done as part of a normal build. 
___
*[activemq/Dockerfile, line 34 at r1](https://reviewable.io/reviews/openmpf/openmpf-docker/157#-MuNV5qt6CpKfzBDtp01:-MuNV5qt6CpKfzBDtp02:bcxn1if) ([raw file](https://github.com/openmpf/openmpf-docker/blob/e2b0033aa2b053d15bd47b62c5586678340e6d8b/activemq/Dockerfile#L34)):*
> ```Dockerfile
> SHELL ["/bin/bash", "-o", "errexit", "-o", "pipefail", "-c"]
> 
> ENV LANG en_US.UTF-8
> ```

When is this needed, and why? I see it in other Dockerfiles too.
___
*[components/java_component_build/Dockerfile, line 50 at r1](https://reviewable.io/reviews/openmpf/openmpf-docker/157#-MuNX69i-qsbrisnGXdG:-MuNX69i-qsbrisnGXdH:b94arzy) ([raw file](https://github.com/openmpf/openmpf-docker/blob/c6f1eccc1eeaddb14dcb3c85f3e10e2dc86ebd32/components/java_component_build/Dockerfile#L50)):*
> ```Dockerfile
> COPY --from=openmpf_build /usr/local/bin/ffmpeg /usr/local/bin/ffprobe /usr/local/bin/
> 
> RUN wget -O- 'https://archive.apache.org/dist/maven/maven-3/3.3.3/binaries/apache-maven-3.3.3-bin.tar.gz' \
> ```

Why switch from `curl` to `wget`?
___
*[components/python/Dockerfile, line 82 at r1](https://reviewable.io/reviews/openmpf/openmpf-docker/157#-MuNXudA5K2Yexvu4B5h:-MuNXudA5K2Yexvu4B5i:bxly8p3) ([raw file](https://github.com/openmpf/openmpf-docker/blob/e2b0033aa2b053d15bd47b62c5586678340e6d8b/components/python/Dockerfile#L82)):*
> ```Dockerfile
> 
> RUN python3 -m venv "$COMPONENT_VIRTUALENV"; \
>     pip3 install --no-cache-dir --upgrade pip;
> ```

Will `pip3` be updated at the same time as installing `python3`?
___
*[openmpf_build/Dockerfile, line 43 at r1](https://reviewable.io/reviews/openmpf/openmpf-docker/157#-MuNaBYVCl_q_Gm3KplN:-MuNaBYVCl_q_Gm3KplO:bc3137y) ([raw file](https://github.com/openmpf/openmpf-docker/blob/c6f1eccc1eeaddb14dcb3c85f3e10e2dc86ebd32/openmpf_build/Dockerfile#L43)):*
> ```Dockerfile
> ENV PIP_COMPILE=0
> 
> ENV DEBIAN_FRONTEND=noninteractive
> ```

Maybe we should set this as an `ARG`? See [this](https://bobcares.com/blog/debian_frontendnoninteractive-docker/).
___
*[workflow_manager/docker-entrypoint.sh, line 80 at r1](https://reviewable.io/reviews/openmpf/openmpf-docker/157#-MuNb42711b3NTCZmsvv:-MuNb42711b3NTCZmsvw:b4421ke) ([raw file](https://github.com/openmpf/openmpf-docker/blob/e2b0033aa2b053d15bd47b62c5586678340e6d8b/workflow_manager/docker-entrypoint.sh#L80)):*
> ```Shell
>     [ ! "$cert" ] && continue
> 
>     "$JAVA_HOME/bin/keytool" -import -alias "mpf_imported_$((cert_counter++))" -file "$cert" -cacerts \
> ```

We don't need to update the Java keystore anymore? Or does `update-ca-certificates` take care of that?

**Review by brosenberg42 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/openmpf/openmpf-docker/157)* status: 16 of 17 files reviewed, 9 unresolved discussions (waiting on @brosenberg42 and @jrobble)

___
*[docker-compose.core.yml, line 46 at r1](https://reviewable.io/reviews/openmpf/openmpf-docker/157#-MuNba4T7yFWFaRw86T3:-Mul3VYwCS4okERS0q0T:bz1dn4o) ([raw file](https://github.com/openmpf/openmpf-docker/blob/c6f1eccc1eeaddb14dcb3c85f3e10e2dc86ebd32/docker-compose.core.yml#L46)):*
<details><summary><i>Previously, jrobble (Jeff Robble) wrote…</i></summary><blockquote>

Why add this?
</blockquote></details>

It is so that it will respond to signals. Without it, it doesn't respond to SIGTERM, which then makes Docker kill it after 10 seconds.
___
*[Jenkinsfile, line 428 at r1](https://reviewable.io/reviews/openmpf/openmpf-docker/157#-MuNORQJBnXjc5XrvGeb:-Mul6Qxp77TKUb-6l-xS:b31p1u2) ([raw file](https://github.com/openmpf/openmpf-docker/blob/c6f1eccc1eeaddb14dcb3c85f3e10e2dc86ebd32/Jenkinsfile#L428)):*
<details><summary><i>Previously, jrobble (Jeff Robble) wrote…</i></summary><blockquote>

I think we should scan all of the images, including those we didn't build (or at least provide an option to enable that). That way we can know of all of the issues before they do scans on the production side. For example, I don't want ActiveMQ issues like the log4j 1 ones to come as a surprise.
</blockquote></details>

This will create a ton of useless logging. If we find a vulnerability in in something like Redis, there isn't anything we can do about it.
___
*[Jenkinsfile, line 441 at r1](https://reviewable.io/reviews/openmpf/openmpf-docker/157#-MuNSf-z0_RKR7E-AGbx:-Mul62y904RWc3Q39AAD:b-qn7gu2) ([raw file](https://github.com/openmpf/openmpf-docker/blob/c6f1eccc1eeaddb14dcb3c85f3e10e2dc86ebd32/Jenkinsfile#L441)):*
<details><summary><i>Previously, jrobble (Jeff Robble) wrote…</i></summary><blockquote>

I think we should alter the status of the job to reflect these findings. How about we mark the build as `UNSTABLE`, as shown [here](https://stackoverflow.com/a/43894382/1424791)?

From the Jenkins API for `UNSTABLE`:

> The build had some errors but they were not fatal. For example, some tests failed.

If a user is actively deciding to enable Trivy scans, I think they would want the job status to reflect the result of the scans.

I could see how changing the status might be an annoyance if the scan is done as part of a normal build. 
</blockquote></details>

There are almost always going to be vulnerabilities in dependencies we use, so your suggestions will result in every build using Trivy to be unstable.
___
*[activemq/Dockerfile, line 34 at r1](https://reviewable.io/reviews/openmpf/openmpf-docker/157#-MuNV5qt6CpKfzBDtp01:-Mul9SDv1Kus1ZXCRjqG:bzh8qrk) ([raw file](https://github.com/openmpf/openmpf-docker/blob/e2b0033aa2b053d15bd47b62c5586678340e6d8b/activemq/Dockerfile#L34)):*
<details><summary><i>Previously, jrobble (Jeff Robble) wrote…</i></summary><blockquote>

When is this needed, and why? I see it in other Dockerfiles too.
</blockquote></details>

I added it when I got build errors related to locale or encoding. From what I remember, I think boost-regex and the Maven assembly plugin need it.
___
*[components/java_component_build/Dockerfile, line 50 at r1](https://reviewable.io/reviews/openmpf/openmpf-docker/157#-MuNX69i-qsbrisnGXdG:-Mul4BZp4VZ_7Fkv-Ns1:bhhcdj) ([raw file](https://github.com/openmpf/openmpf-docker/blob/c6f1eccc1eeaddb14dcb3c85f3e10e2dc86ebd32/components/java_component_build/Dockerfile#L50)):*
<details><summary><i>Previously, jrobble (Jeff Robble) wrote…</i></summary><blockquote>

Why switch from `curl` to `wget`?
</blockquote></details>

The examples I saw for Ubuntu all used it. Neither is installed by default and wget is a tiny bit smaller.
___
*[components/python/Dockerfile, line 82 at r1](https://reviewable.io/reviews/openmpf/openmpf-docker/157#-MuNXudA5K2Yexvu4B5h:-Mul4R1p2h1K-p327dHX:b-y4110j) ([raw file](https://github.com/openmpf/openmpf-docker/blob/e2b0033aa2b053d15bd47b62c5586678340e6d8b/components/python/Dockerfile#L82)):*
<details><summary><i>Previously, jrobble (Jeff Robble) wrote…</i></summary><blockquote>

Will `pip3` be updated at the same time as installing `python3`?
</blockquote></details>

We want to use the version of pip that comes from `apt-get`. It may lag behind the latest version of pip by a little bit. 
___
*[openmpf_build/Dockerfile, line 43 at r1](https://reviewable.io/reviews/openmpf/openmpf-docker/157#-MuNaBYVCl_q_Gm3KplN:-MulDEte4gyTjLoXCD4p:b-896fix) ([raw file](https://github.com/openmpf/openmpf-docker/blob/c6f1eccc1eeaddb14dcb3c85f3e10e2dc86ebd32/openmpf_build/Dockerfile#L43)):*
<details><summary><i>Previously, jrobble (Jeff Robble) wrote…</i></summary><blockquote>

Maybe we should set this as an `ARG`? See [this](https://bobcares.com/blog/debian_frontendnoninteractive-docker/).
</blockquote></details>

Done.
___
*[workflow_manager/docker-entrypoint.sh, line 80 at r1](https://reviewable.io/reviews/openmpf/openmpf-docker/157#-MuNb42711b3NTCZmsvv:-Mul5d-A1hDHYg2Fp5pW:b-gpz0d6) ([raw file](https://github.com/openmpf/openmpf-docker/blob/e2b0033aa2b053d15bd47b62c5586678340e6d8b/workflow_manager/docker-entrypoint.sh#L80)):*
<details><summary><i>Previously, jrobble (Jeff Robble) wrote…</i></summary><blockquote>

We don't need to update the Java keystore anymore? Or does `update-ca-certificates` take care of that?
</blockquote></details>

On Ubuntu, Java will also check the system's certificates.

**Review by jrobble — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/openmpf/openmpf-docker/157)* status: 16 of 17 files reviewed, 3 unresolved discussions (waiting on @brosenberg42 and @jrobble)

___
*[Jenkinsfile, line 428 at r1](https://reviewable.io/reviews/openmpf/openmpf-docker/157#-MuNORQJBnXjc5XrvGeb:-MulRckD55pkGu-eg6pq:b-amubk1) ([raw file](https://github.com/openmpf/openmpf-docker/blob/c6f1eccc1eeaddb14dcb3c85f3e10e2dc86ebd32/Jenkinsfile#L428)):*
<details><summary><i>Previously, brosenberg42 wrote…</i></summary><blockquote>

This will create a ton of useless logging. If we find a vulnerability in in something like Redis, there isn't anything we can do about it.
</blockquote></details>

We still need to report it or get it waived. 
___
*[Jenkinsfile, line 441 at r1](https://reviewable.io/reviews/openmpf/openmpf-docker/157#-MuNSf-z0_RKR7E-AGbx:-MulSBr09XnaTAAESUJp:b-vtmstx) ([raw file](https://github.com/openmpf/openmpf-docker/blob/c6f1eccc1eeaddb14dcb3c85f3e10e2dc86ebd32/Jenkinsfile#L441)):*
<details><summary><i>Previously, brosenberg42 wrote…</i></summary><blockquote>

There are almost always going to be vulnerabilities in dependencies we use, so your suggestions will result in every build using Trivy to be unstable.
</blockquote></details>

I hear what you're saying. I think it boils down to the use case.

I certainly wouldn't want to enable Trivy on develop and master builds that automatically get kicked off, or on pull request builds; however, if I'm initiating a build for the sole purpose of looking at the Trivy results, then I probably want the state of the build to reflect the results. 

If we're going to enable Trivy scans on the master builds that we tag for GA release then I agree that we don't want to mark those as unstable.

When do you think it makes the most sense to kick off a build with Trivy scans enabled? Do you think they should be part of the GA release build, or a separate build altogether?

Another, additional, option is to consider adding Trivy scans to a nightly master build. If nightly, I don't want to have to look at the logs every time to determine that there is a new vuln. We could consider whitelisting things that are waived.

**Review by jrobble — COMMENTED** [review]
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/openmpf/openmpf-docker/157)* status: all files reviewed (commit messages unreviewed), 3 unresolved discussions (waiting on @brosenberg42)

**Comment by jrobble** [comment]
___
*[Jenkinsfile, line 441 at r1](https://reviewable.io/reviews/openmpf/openmpf-docker/157#-MuNSf-z0_RKR7E-AGbx:-MulZvG38aIbxE-xsgEz:b7fgnj1) ([raw file](https://github.com/openmpf/openmpf-docker/blob/c6f1eccc1eeaddb14dcb3c85f3e10e2dc86ebd32/Jenkinsfile#L441)):*
> adding Trivy scans to a nightly master build

This could be on the clean build, since that pulls in new dependencies.

**Comment by jrobble** [comment]
___
*[Jenkinsfile, line 441 at r1](https://reviewable.io/reviews/openmpf/openmpf-docker/157#-MuNSf-z0_RKR7E-AGbx:-MuqSV9O24F8k_nmljVK:b-4ec3rb) ([raw file](https://github.com/openmpf/openmpf-docker/blob/c6f1eccc1eeaddb14dcb3c85f3e10e2dc86ebd32/Jenkinsfile#L441)):*
<details><summary><i>Previously, jrobble (Jeff Robble) wrote…</i></summary><blockquote>

> adding Trivy scans to a nightly master build

This could be on the clean build, since that pulls in new dependencies.
</blockquote></details>

We decided to do the Trivy scans as part of the release builds. We also considered doing them proactively / periodically, but decided instead to do them on-demand.

**Review by jrobble — APPROVED** [review]
> Reviewed 2 of 2 files at r3, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/openmpf/openmpf-docker/157)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @brosenberg42)

___
*[activemq/Dockerfile, line 43 at r1](https://reviewable.io/reviews/openmpf/openmpf-docker/157#-MspjgPVAHhMaNS00GT3:-Mw8AwRABk-KsGyR6VGP:b-r264cn) ([raw file](https://github.com/openmpf/openmpf-docker/blob/c6f1eccc1eeaddb14dcb3c85f3e10e2dc86ebd32/activemq/Dockerfile#L43)):*
<details><summary><i>Previously, jrobble (Jeff Robble) wrote…</i></summary><blockquote>

Dropping a note here that we need to either update to ActiveMQ 5.17.0 to address Trivy scan issues, or get sign-off by the end users.
</blockquote></details>

Resolved by updating to 5.16.4.

**Pull request merged**
