### PR TITLE
Feat/file env vars

### PR DESCRIPTION
**Pull request by brosenberg42**
**Issues:**
- https://github.com/openmpf/openmpf/issues/1745

**Related PRs:**
- https://github.com/openmpf/openmpf-projects/pull/8

- - -
This change is [Reviewable](https://reviewable.io/reviews/openmpf/openmpf-docker/207)

### CODE REVIEW

**Review by jrobble — CHANGES_REQUESTED** [review]
> Reviewed 11 of 11 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/openmpf/openmpf-docker/207)* status: all files reviewed, 1 unresolved discussion (waiting on @brosenberg42)

___
*[`openmpf_build/scripts/set-file-env-vars.sh` line 79 at r1](https://reviewable.io/reviews/openmpf/openmpf-docker/207#-Np_wecQ2vSaab0F92SO:-Np_wecS2nj_N6ZA1vgG:b27j3wz) ([raw file](https://github.com/openmpf/openmpf-docker/blob/051e8c9484bf4c7bd7b20e20eeb182326639eb04/openmpf_build/scripts/set-file-env-vars.sh#L79)):*
> ```Shell
> }
> 
> >&2 set_file_env_vars
> ```

Please add a comment for these lines.

**Review by jrobble — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/openmpf/openmpf-docker/207)* status: all files reviewed, 2 unresolved discussions (waiting on @brosenberg42)

___
*[`README.md` line 386 at r1](https://reviewable.io/reviews/openmpf/openmpf-docker/207#-NpbalKf35Qepow5HXI-:-NpbalKgAvOqzwStth31:bhc9nwx) ([raw file](https://github.com/openmpf/openmpf-docker/blob/051e8c9484bf4c7bd7b20e20eeb182326639eb04/README.md#L386)):*
> ```Markdown
>   default.
> 
> Below is an example of how a user could set `KEYSTORE_PASSWORD` environment variable using a secret.
> ```

Say "example of a partial Docker Compose file that shows how ..."

It should be obvious that it's partial, but this guide does hold of the hand of the reader through a lot of the other sections.

**Review by brosenberg42 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/openmpf/openmpf-docker/207)* status: 9 of 11 files reviewed, 2 unresolved discussions (waiting on @jrobble)

___
*[`README.md` line 386 at r1](https://reviewable.io/reviews/openmpf/openmpf-docker/207#-NpbalKf35Qepow5HXI-:-Npe8v7a3hVy269DxX2s:b-896fix) ([raw file](https://github.com/openmpf/openmpf-docker/blob/051e8c9484bf4c7bd7b20e20eeb182326639eb04/README.md#L386)):*
<details><summary><i>Previously, jrobble (Jeff Robble) wrote…</i></summary><blockquote>

Say "example of a partial Docker Compose file that shows how ..."

It should be obvious that it's partial, but this guide does hold of the hand of the reader through a lot of the other sections.
</blockquote></details>

Done.

**Review by brosenberg42 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/openmpf/openmpf-docker/207)* status: 9 of 11 files reviewed, 2 unresolved discussions (waiting on @jrobble)

___
*[`openmpf_build/scripts/set-file-env-vars.sh` line 79 at r1](https://reviewable.io/reviews/openmpf/openmpf-docker/207#-Np_wecQ2vSaab0F92SO:-NpeCiEt49-j3IFnOaDW:b-896fix) ([raw file](https://github.com/openmpf/openmpf-docker/blob/051e8c9484bf4c7bd7b20e20eeb182326639eb04/openmpf_build/scripts/set-file-env-vars.sh#L79)):*
<details><summary><i>Previously, jrobble (Jeff Robble) wrote…</i></summary><blockquote>

Please add a comment for these lines.
</blockquote></details>

Done.

**Review by jrobble — APPROVED** [review]
> Reviewed 2 of 2 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/openmpf/openmpf-docker/207)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @brosenberg42)

**Pull request merged**
