### PR TITLE
Standalone Docker Python Executor

### PR DESCRIPTION
**Pull request by jrobble**
This change is [Reviewable](https://reviewable.io/reviews/openmpf/openmpf-docker/28)

### CODE REVIEW

**Comment by brosenberg42** [comment]
> I'm fine with asking the users to create a hardlink.

I am not planning on using the hard link nor run.sh in the final product. I am planning on using openmpf_runtime as the build context in the final product. I have the hard link for now because I am constantly rebuilding the images. In future development, I won't need to rebuild the image as often, so I am not too worried about using openmpf_runtime as the build context. 

I also wasn't planning on including run.sh in the final product. I am planning on renaming and moving that file somewhere else on my machine. I just included it in the branch to make things more convenient for you.

**Comment by jrobble** [comment]
___
*[openmpf_runtime/python_executor/README.md, line 79 at r2](https://reviewable.io/reviews/openmpf/openmpf-docker/28#-LbcxNx35P7MLrgmaJR4:-LbcxNx35P7MLrgmaJR5:bj8csa) ([raw file](https://github.com/openmpf/openmpf-docker/blob/2ba1ba63b95560158ae1f406fbac42aba8511b9f/openmpf_runtime/python_executor/README.md#L79)):*
> ```Markdown
>     --network openmpf_default \
>     -v openmpf_shared_data:/opt/mpf/share \
>     -e WFM_USER=<wfm_admin_user> \
> ```

It would help to mention at the top of this file what the settings for WFM_USER and WFM_PASSWORD are if the user never changed the default admin username and password, or at least mention that those are the same creds a user would use to log into the web UI.

**Comment by jrobble** [comment]
___
*[openmpf_runtime/python_executor/README.md, line 1 at r2](https://reviewable.io/reviews/openmpf/openmpf-docker/28#-LbdK_e56SSAp3LoiSEE:-LbdK_e56SSAp3LoiSEF:brkjiho) ([raw file](https://github.com/openmpf/openmpf-docker/blob/2ba1ba63b95560158ae1f406fbac42aba8511b9f/openmpf_runtime/python_executor/README.md#L1)):*
> ```Markdown
> How to build the openmpf_python_executor base image
> ```

Before jumping into to the "How to", let's provide an Overview section that provides some motivation for why a developer would use this image. Additionally, we should explain the difference between the two approaches and what the image does.

Regarding that last sentence, you can lift a lot of the content from the email I sent out, word-for-word, starting with "As a developer, you have two options ...", and ending with "... needs to COPY files out of the install.tar."

**Comment by jrobble** [comment]
___
*[openmpf_runtime/python_executor/docker-entrypoint.py, line 146 at r3](https://reviewable.io/reviews/openmpf/openmpf-docker/28#-LbiSPFe-kgpQG3n5A6K:-LbiRooi9BNWkSILk8OK:b-aw6486) ([raw file](https://github.com/openmpf/openmpf-docker/blob/b29b64e4be17bb4ab00b6cebbea632792f6e1c22/openmpf_runtime/python_executor/docker-entrypoint.py#L146)):*
> ```Python
>                       'but an "https://" URL was used. Trying again with:', new_url)
>                 url = new_url
>                 continue
> ```

When switching from HTTP to HTTPS above you call `post_descriptor()` to give it one more chance. Here, when switching from HTTPS to HTTP you `continue` the loop instead of calling `post_descriptor()`. Why the difference?

I'm assuming it may have something to do with the fact that other connection errors may arise once you've resolved the SSLError, so you want to give the loop a chance to resolve them too?

**Pull request merged**
