### PR TITLE
Added clip-detection and clip-detection-server to docker-compose.comp…

### PR DESCRIPTION
**Pull request by ZachCafego**
…onents.yml file.

**Issues:**

- https://github.com/openmpf/openmpf/issues/1535

**Related PRs:**

- https://github.com/openmpf/openmpf-components/pull/326

- - -
This change is [Reviewable](https://reviewable.io/reviews/openmpf/openmpf-docker/189)

### CODE REVIEW

**Review by jrobble — CHANGES_REQUESTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/openmpf/openmpf-docker/189)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @ZachCafego)

___
*[`docker-compose.components.yml` line 115 at r1](https://reviewable.io/reviews/openmpf/openmpf-docker/189#-NTzccDJ3mT6GAtQL8pb:-NTzccDJ3mT6GAtQL8pc:bpe4j41) ([raw file](https://github.com/openmpf/openmpf-docker/blob/103ea2050c24e7c0a6736f4635e77526e2d0841a/docker-compose.components.yml#L115)):*
> ```YAML
>       memlock: -1  # don't limit locked-in memory (prevent paging)
>       stack: 67108864  # 8 GiB
>     ports:
> ```

Need to comment this out.

**Review by ZachCafego — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/openmpf/openmpf-docker/189)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @jrobble and @ZachCafego)

___
*[`docker-compose.components.yml` line 115 at r1](https://reviewable.io/reviews/openmpf/openmpf-docker/189#-NTzccDJ3mT6GAtQL8pb:-NU33q4f1psJGoAv-2Uv:b-896fix) ([raw file](https://github.com/openmpf/openmpf-docker/blob/103ea2050c24e7c0a6736f4635e77526e2d0841a/docker-compose.components.yml#L115)):*
<details><summary><i>Previously, jrobble (Jeff Robble) wrote…</i></summary><blockquote>

Need to comment this out.
</blockquote></details>

Done.

**Review by jrobble — COMMENTED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/openmpf/openmpf-docker/189)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ZachCafego)

**Review by jrobble — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/openmpf/openmpf-docker/189)* status: 0 of 1 files reviewed, all discussions resolved (waiting on @ZachCafego)

___
*[`docker-compose.components.yml` line 107 at r3](https://reviewable.io/reviews/openmpf/openmpf-docker/189#-NVoya2q0aFCdeGIhAib:-NVoya2q0aFCdeGIhAic:b-3ev060) ([raw file](https://github.com/openmpf/openmpf-docker/blob/0c151ce34e8dbeacdb035721274b8dba47612db8/docker-compose.components.yml#L107)):*
> ```YAML
>   
>   clip-detection-server:
>     <<: *detection-component-base
> ```

I addressed the following issue and merged in the changes. Just leaving the comment for posterity:

---

Remove this `<<` line. `ocv-yolo-detection-server` doesn't have it.
___
*[`docker-compose.components.yml` line 128 at r3](https://reviewable.io/reviews/openmpf/openmpf-docker/189#-NW3SHXq03J_Y1VkM73Y:-NW3SHXq03J_Y1VkM73Z:b-927siw) ([raw file](https://github.com/openmpf/openmpf-docker/blob/0c151ce34e8dbeacdb035721274b8dba47612db8/docker-compose.components.yml#L128)):*
> ```YAML
>               --strict-model-config=false,
>               --model-control-mode=explicit,
>               --load-model=ip-clip-512,
> ```

I addressed the following issues and merged in the changes. Just leaving the comment for posterity.

---

I'm getting this error:

```json
   "errors": [
      {
         "mediaId": 7,
         "details": [
            {
               "source": "CLIP",
               "code": "UNRECOGNIZED_DETECTION_ERROR",
               "message": "An error occurred while invoking the \"get_detections_from_image\" method on the Python component: [StatusCode.UNAVAILABLE] Request for unknown model: 'ip_clip_512' is not found"
            }
         ]
      }
   ],
```

This should be:

```python
--load-model=ip_clip_512,
```

This is because the Docker image has `/models/ip_clip_512`.

---

Once I made that change I got the following in the server log:

```
error: creating server: Invalid argument - load failed for model 'ip_clip_512': version 1: Invalid argument: unable to load model 'ip_clip_512', configuration expects 0 inputs, model provides 1;
```

I tracked this down and the issue is that the Triton server expects the file to be `/models/ip_clip_512/config.pbtxt`. It was not finding the file until I copied it to that location.

**Review by jrobble — COMMENTED** [review]
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/openmpf/openmpf-docker/189)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ZachCafego)

**Review by jrobble — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/openmpf/openmpf-docker/189#-:-NXLloOk6QyWmv13mjH9:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ZachCafego)

**Pull request merged**
