### PR TITLE
CLI keep component alive

### PR DESCRIPTION
**Pull request by brosenberg42**
**Issues:**
- https://github.com/openmpf/openmpf/issues/1436

---
This change is [Reviewable](https://reviewable.io/reviews/openmpf/openmpf-docker/158)

### CODE REVIEW

**Review by jrobble — CHANGES_REQUESTED** [review]
> Reviewed 8 of 12 files at r1, 3 of 3 files at r2, 3 of 3 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/openmpf/openmpf-docker/158)* status: all files reviewed, 6 unresolved discussions (waiting on @brosenberg42)

___
*[`CLI_RUNNER.md` line 143 at r2](https://reviewable.io/reviews/openmpf/openmpf-docker/158#-N3ZoUZaAeuEi8-V7CZK:-N3ZoUZaAeuEi8-V7CZL:bb1n2hd) ([raw file](https://github.com/openmpf/openmpf-docker/blob/a40d9611240a6e449eb454fb4a7f60520e1f5610/CLI_RUNNER.md#L143)):*
> ```Markdown
> ```
> 
> ### Idle Timeout ###
> ```

I think we should move this section below the sections that explain what the ExecutorProcess and ComponentServer are.
___
*[`CLI_RUNNER.md` line 182 at r3](https://reviewable.io/reviews/openmpf/openmpf-docker/158#-N3aRf817rhvRibC33lk:-N3aRf817rhvRibC33ll:b-a737x8) ([raw file](https://github.com/openmpf/openmpf-docker/blob/ab1fa073a80351b4ebca8b6e58d8437f62221052/CLI_RUNNER.md#L182)):*
> ```Markdown
> 
> #### Protocol ####
> 1. Either:
> ```

This is good intel, but this first step can be misinterpreted to mean that the user has to do one of those two things in addition to what they are already doing. 

It might help to explain that `ComponentServer` is started manually when the user does `docker run ... -d` and that the other case when the client is started without the server is when the user does `docker run` not in daemon mode.

Also, I feel like for a typical user this intel might be a bit scary, so maybe we should consider moving it to an Appendix section to this md file, or moving it to a different md file we link to from this one.
___
*[`components/cli_runner/mpf_cli_client.py` line 61 at r2](https://reviewable.io/reviews/openmpf/openmpf-docker/158#-N3a6EsLAPWO_fq2OUz5:-N3a6EsLAPWO_fq2OUz6:b-xx1c3e) ([raw file](https://github.com/openmpf/openmpf-docker/blob/a40d9611240a6e449eb454fb4a7f60520e1f5610/components/cli_runner/mpf_cli_client.py#L61)):*
> ```Python
>     if response == b'':
>         print('ERROR: Server closed connection before completing the job.', file=sys.stderr)
>         sys.exit(6)
> ```

Why 6?
___
*[`components/cli_runner/mpf_cli_executor_process.py` line 102 at r2](https://reviewable.io/reviews/openmpf/openmpf-docker/158#-N3_HkIo-ixupVCGaGTF:-N3_HkIo-ixupVCGaGTG:bb6fj8c) ([raw file](https://github.com/openmpf/openmpf-docker/blob/a40d9611240a6e449eb454fb4a7f60520e1f5610/components/cli_runner/mpf_cli_executor_process.py#L102)):*
> ```Python
>             runner_thread.join()
>             if runner_exception is not None:
>                 # Prefer reporting runner thread's exception over the watcher threads exception.
> ```

"watcher thread's exception"
___
*[`components/cli_runner/mpf_cli_executor_process.py` line 302 at r2](https://reviewable.io/reviews/openmpf/openmpf-docker/158#-N3a1nCjDBju7fwyi-L0:-N3a1nCjDBju7fwyi-L1:bx68p2q) ([raw file](https://github.com/openmpf/openmpf-docker/blob/a40d9611240a6e449eb454fb4a7f60520e1f5610/components/cli_runner/mpf_cli_executor_process.py#L302)):*
> ```Python
>             return os.fdopen(stdin_fd, 'r'), os.fdopen(stdout_fd, 'w'), os.fdopen(stderr_fd, 'w')
>         except Exception:
>             # We need to be careful here to only call either os.close(fd) or close on the file
> ```

I'm thinking about how to reword for clarity. Maybe:

```
# We need to be careful here to only call either os.close(fd) or close on the file
# object returned from os.fdopen, not both. Otherwise,
# by the time we call os.close(fd), that file descriptor may refer to a different file
# that shouldn't be closed.
```
___
*[`components/cli_runner/mpf_cli_server.py` line 246 at r3](https://reviewable.io/reviews/openmpf/openmpf-docker/158#-N3aQbb11SLoaSAGWoPJ:-N3aQbb11SLoaSAGWoPK:b8czzam) ([raw file](https://github.com/openmpf/openmpf-docker/blob/ab1fa073a80351b4ebca8b6e58d8437f62221052/components/cli_runner/mpf_cli_server.py#L246)):*
> ```Python
> 
> 
> class ExecutorProcessInfo:
> ```

Nitpick: Calling this "Info" seems a bit strange since it submits the job. Maybe "Handler" is a better term?

**Review by brosenberg42 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/openmpf/openmpf-docker/158)* status: 9 of 12 files reviewed, 6 unresolved discussions (waiting on @jrobble)

___
*[`CLI_RUNNER.md` line 143 at r2](https://reviewable.io/reviews/openmpf/openmpf-docker/158#-N3ZoUZaAeuEi8-V7CZK:-N3dDR9OAfwaDAyFptGQ:bgxoi1a) ([raw file](https://github.com/openmpf/openmpf-docker/blob/a40d9611240a6e449eb454fb4a7f60520e1f5610/CLI_RUNNER.md#L143)):*
<details><summary><i>Previously, jrobble (Jeff Robble) wrote…</i></summary><blockquote>

I think we should move this section below the sections that explain what the ExecutorProcess and ComponentServer are.
</blockquote></details>

I think configuration options are more likely to be relevant to a typical user. The sections below this are really more for other developers who might work on this.
___
*[`CLI_RUNNER.md` line 182 at r3](https://reviewable.io/reviews/openmpf/openmpf-docker/158#-N3aRf817rhvRibC33lk:-N3dPBYK1msaHinpbLtY:b-896fix) ([raw file](https://github.com/openmpf/openmpf-docker/blob/ab1fa073a80351b4ebca8b6e58d8437f62221052/CLI_RUNNER.md#L182)):*
<details><summary><i>Previously, jrobble (Jeff Robble) wrote…</i></summary><blockquote>

This is good intel, but this first step can be misinterpreted to mean that the user has to do one of those two things in addition to what they are already doing. 

It might help to explain that `ComponentServer` is started manually when the user does `docker run ... -d` and that the other case when the client is started without the server is when the user does `docker run` not in daemon mode.

Also, I feel like for a typical user this intel might be a bit scary, so maybe we should consider moving it to an Appendix section to this md file, or moving it to a different md file we link to from this one.
</blockquote></details>

Done.
___
*[`components/cli_runner/mpf_cli_client.py` line 61 at r2](https://reviewable.io/reviews/openmpf/openmpf-docker/158#-N3a6EsLAPWO_fq2OUz5:-N3dFvDb4kPXRNDMZBa5:b7nthma) ([raw file](https://github.com/openmpf/openmpf-docker/blob/a40d9611240a6e449eb454fb4a7f60520e1f5610/components/cli_runner/mpf_cli_client.py#L61)):*
<details><summary><i>Previously, jrobble (Jeff Robble) wrote…</i></summary><blockquote>

Why 6?
</blockquote></details>

I think I just wanted a unique error code for this situation.
___
*[`components/cli_runner/mpf_cli_executor_process.py` line 102 at r2](https://reviewable.io/reviews/openmpf/openmpf-docker/158#-N3_HkIo-ixupVCGaGTF:-N3dG4sVDA_pLFAsU5ZA:b-896fix) ([raw file](https://github.com/openmpf/openmpf-docker/blob/a40d9611240a6e449eb454fb4a7f60520e1f5610/components/cli_runner/mpf_cli_executor_process.py#L102)):*
<details><summary><i>Previously, jrobble (Jeff Robble) wrote…</i></summary><blockquote>

"watcher thread's exception"
</blockquote></details>

Done.
___
*[`components/cli_runner/mpf_cli_executor_process.py` line 302 at r2](https://reviewable.io/reviews/openmpf/openmpf-docker/158#-N3a1nCjDBju7fwyi-L0:-N3dInzDDVb4m-9Tdav4:b-pwmx6i) ([raw file](https://github.com/openmpf/openmpf-docker/blob/a40d9611240a6e449eb454fb4a7f60520e1f5610/components/cli_runner/mpf_cli_executor_process.py#L302)):*
<details><summary><i>Previously, jrobble (Jeff Robble) wrote…</i></summary><blockquote>

I'm thinking about how to reword for clarity. Maybe:

```
# We need to be careful here to only call either os.close(fd) or close on the file
# object returned from os.fdopen, not both. Otherwise,
# by the time we call os.close(fd), that file descriptor may refer to a different file
# that shouldn't be closed.
```
</blockquote></details>

My original comment is technically wrong. IIRC, the code that previously did this was more complicated.
___
*[`components/cli_runner/mpf_cli_server.py` line 246 at r3](https://reviewable.io/reviews/openmpf/openmpf-docker/158#-N3aQbb11SLoaSAGWoPJ:-N3dGQ1D4gQhoo7pUYQ9:b-896fix) ([raw file](https://github.com/openmpf/openmpf-docker/blob/ab1fa073a80351b4ebca8b6e58d8437f62221052/components/cli_runner/mpf_cli_server.py#L246)):*
<details><summary><i>Previously, jrobble (Jeff Robble) wrote…</i></summary><blockquote>

Nitpick: Calling this "Info" seems a bit strange since it submits the job. Maybe "Handler" is a better term?
</blockquote></details>

Done.

**Review by jrobble — CHANGES_REQUESTED** [review]
> Reviewed 2 of 3 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/openmpf/openmpf-docker/158)* status: 11 of 12 files reviewed, 2 unresolved discussions (waiting on @brosenberg42 and @jrobble)

___
*[`CLI_RUNNER.md` line 145 at r4](https://reviewable.io/reviews/openmpf/openmpf-docker/158#-N3e32h_DkLxVYuin560:-N3e32h_DkLxVYuin561:brx6i95) ([raw file](https://github.com/openmpf/openmpf-docker/blob/1c5e56c5516b378aa0e9532c760eb9bc9f6cf941/CLI_RUNNER.md#L145)):*
> ```Markdown
> ### Idle Timeout ###
> The `COMPONENT_SERVER_IDLE_TIMEOUT` environment variable can be used to configure the idle timeout.
> It should be set when the Docker container is started. It always applies to ExecutorProcesses
> ```

I updated the documentation [here](https://github.com/openmpf/openmpf-docker/blob/jrobble/cli-keep-alive/CLI_RUNNER.md). Please merge that in and modify if necessary.
___
*[`components/cli_runner/mpf_cli_server.py` line 191 at r4](https://reviewable.io/reviews/openmpf/openmpf-docker/158#-N3uaRYf1uZNtWW6BFy9:-N3uaRYg5Ah83G0uDhPR:bg07xum) ([raw file](https://github.com/openmpf/openmpf-docker/blob/1c5e56c5516b378aa0e9532c760eb9bc9f6cf941/components/cli_runner/mpf_cli_server.py#L191)):*
> ```Python
>         while True:
>             self._remove_dead_processes()
>             log.debug(self._stats)
> ```

This may not be a problem. I just want to confirm this is expected. I saw the same line printed out multiple times:

```
INFO  457 [mpf_cli_executor_process.py:133] - Executor process exiting due to idle timeout.
DEBUG 1 [mpf_cli_server.py:191] - Jobs submitted = 25, max active processes = 25, processes started = 25, exited = 24, errors = 0
DEBUG 1 [mpf_cli_server.py:191] - Jobs submitted = 25, max active processes = 25, processes started = 25, exited = 24, errors = 0
DEBUG 1 [mpf_cli_server.py:191] - Jobs submitted = 25, max active processes = 25, processes started = 25, exited = 24, errors = 0
```

I had `COMPONENT_SERVER_IDLE_TIMEOUT=0`.
___
*[`components/cli_runner/mpf_cli_server.py` line 237 at r4](https://reviewable.io/reviews/openmpf/openmpf-docker/158#-N3uWAv13Gzt_kDUi6qC:-N3uWAv2799-ISz7yqau:b-1xnnrj) ([raw file](https://github.com/openmpf/openmpf-docker/blob/1c5e56c5516b378aa0e9532c760eb9bc9f6cf941/components/cli_runner/mpf_cli_server.py#L237)):*
> ```Python
> 
>     def __str__(self):
>         return f'Jobs submitted = {self.job_count}, max active processes = {self.max_active}, ' \
> ```

It could be useful to print the number of currently active processes or number of executors in the pool.

**Review by jrobble — COMMENTED** [review]
> Reviewed 1 of 3 files at r4.
> *[Reviewable](https://reviewable.io/reviews/openmpf/openmpf-docker/158)* status: all files reviewed, 2 unresolved discussions (waiting on @brosenberg42)

**Review by jrobble — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/openmpf/openmpf-docker/158)* status: all files reviewed, 2 unresolved discussions (waiting on @brosenberg42)

___
*[`CLI_RUNNER.md` line 145 at r4](https://reviewable.io/reviews/openmpf/openmpf-docker/158#-N3e32h_DkLxVYuin560:-N3v2NLv6jJ2a2GoYWG5:b-cfiwna) ([raw file](https://github.com/openmpf/openmpf-docker/blob/1c5e56c5516b378aa0e9532c760eb9bc9f6cf941/CLI_RUNNER.md#L145)):*
<details><summary><i>Previously, jrobble (Jeff Robble) wrote…</i></summary><blockquote>

I updated the documentation [here](https://github.com/openmpf/openmpf-docker/blob/jrobble/cli-keep-alive/CLI_RUNNER.md). Please merge that in and modify if necessary.
</blockquote></details>

[Better link](https://github.com/openmpf/openmpf-docker/commit/d91287010629e0d66d3a7bce78eecbb2740b878b)

**Comment by brosenberg42** [comment]
*[`components/cli_runner/mpf_cli_server.py` line 191 at r4](https://reviewable.io/reviews/openmpf/openmpf-docker/158#-N3uaRYf1uZNtWW6BFy9:-N3yQIocDUuCG105FNS0:bt41ot5) ([raw file](https://github.com/openmpf/openmpf-docker/blob/1c5e56c5516b378aa0e9532c760eb9bc9f6cf941/components/cli_runner/mpf_cli_server.py#L191)):*
<details><summary><i>Previously, jrobble (Jeff Robble) wrote…</i></summary><blockquote>

This may not be a problem. I just want to confirm this is expected. I saw the same line printed out multiple times:

```
INFO  457 [mpf_cli_executor_process.py:133] - Executor process exiting due to idle timeout.
DEBUG 1 [mpf_cli_server.py:191] - Jobs submitted = 25, max active processes = 25, processes started = 25, exited = 24, errors = 0
DEBUG 1 [mpf_cli_server.py:191] - Jobs submitted = 25, max active processes = 25, processes started = 25, exited = 24, errors = 0
DEBUG 1 [mpf_cli_server.py:191] - Jobs submitted = 25, max active processes = 25, processes started = 25, exited = 24, errors = 0
```

I had `COMPONENT_SERVER_IDLE_TIMEOUT=0`.
</blockquote></details>

I did some testing. This is occurring because the process's sentinel becomes ready slightly before the process actually exits.

**Review by jrobble — APPROVED** [review]
> Reviewed 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/openmpf/openmpf-docker/158)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @brosenberg42)

**Review by brosenberg42 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/openmpf/openmpf-docker/158)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @brosenberg42)

___
*[`CLI_RUNNER.md` line 145 at r4](https://reviewable.io/reviews/openmpf/openmpf-docker/158#-N3e32h_DkLxVYuin560:-N3yq2JI7jR9NhLT9B-v:b-896fix) ([raw file](https://github.com/openmpf/openmpf-docker/blob/1c5e56c5516b378aa0e9532c760eb9bc9f6cf941/CLI_RUNNER.md#L145)):*
<details><summary><i>Previously, jrobble (Jeff Robble) wrote…</i></summary><blockquote>

[Better link](https://github.com/openmpf/openmpf-docker/commit/d91287010629e0d66d3a7bce78eecbb2740b878b)
</blockquote></details>

Done.
___
*[`components/cli_runner/mpf_cli_server.py` line 237 at r4](https://reviewable.io/reviews/openmpf/openmpf-docker/158#-N3uWAv13Gzt_kDUi6qC:-N3yq4_oCTwvHgDV7i60:b-jhymee) ([raw file](https://github.com/openmpf/openmpf-docker/blob/1c5e56c5516b378aa0e9532c760eb9bc9f6cf941/components/cli_runner/mpf_cli_server.py#L237)):*
<details><summary><i>Previously, jrobble (Jeff Robble) wrote…</i></summary><blockquote>

It could be useful to print the number of currently active processes or number of executors in the pool.
</blockquote></details>

That information is there. It is `started - exited`

**Pull request merged**
