### PR TITLE
Enable specifying the Docker images to push.

### PR DESCRIPTION
**Pull request by jrobble**
**Issues:**

- https://github.com/openmpf/openmpf/issues/1800

- - -
This change is [Reviewable](https://reviewable.io/reviews/openmpf/openmpf-docker/215)

### CODE REVIEW

**Review by jrobble — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/openmpf/openmpf-docker/215)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @brosenberg42 and @jrobble)

___
*[`Jenkinsfile` line 472 at r1](https://reviewable.io/reviews/openmpf/openmpf-docker/215#-NxCvuqcBdjl_EAYG8ni:-Nyap_rrCOwsyin4OZ0D:b-896fix) ([raw file](https://github.com/openmpf/openmpf-docker/blob/f2b42a9eafc149e63efe2894532176e0588f8fd1/Jenkinsfile#L472)):*
<details><summary><i>Previously, brosenberg42 wrote…</i></summary><blockquote>

You shouldn't need to `cd` when `COMPOSE_FILE` is set.
</blockquote></details>

Done.

**Comment by jrobble** [comment]
*[`Jenkinsfile` line 472 at r1](https://reviewable.io/reviews/openmpf/openmpf-docker/215#-NxCvuqcBdjl_EAYG8ni:-NyaubRSBKqzei41HI9i:b4psta8) ([raw file](https://github.com/openmpf/openmpf-docker/blob/f2b42a9eafc149e63efe2894532176e0588f8fd1/Jenkinsfile#L472)):*
<details><summary><i>Previously, jrobble (Jeff Robble) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Removing it results in:

```
+ docker compose config --images
stat /1TB/jenkins/workspace/openmpf-docker-pull-request/docker-compose.core.yml: no such file or directory
```

**Comment by jrobble** [comment]
*[`Jenkinsfile` line 472 at r1](https://reviewable.io/reviews/openmpf/openmpf-docker/215#-NxCvuqcBdjl_EAYG8ni:-Nyb1SAM9lgcPFmpfJoK:bsct312) ([raw file](https://github.com/openmpf/openmpf-docker/blob/f2b42a9eafc149e63efe2894532176e0588f8fd1/Jenkinsfile#L472)):*
<details><summary><i>Previously, jrobble (Jeff Robble) wrote…</i></summary><blockquote>

Removing it results in:

```
+ docker compose config --images
stat /1TB/jenkins/workspace/openmpf-docker-pull-request/docker-compose.core.yml: no such file or directory
```
</blockquote></details>

I added `dir (openmpfDockerRepo.path) {` to address this. That is done in other places in the `Jenkinsfile`.

**Review by brosenberg42 — APPROVED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/openmpf/openmpf-docker/215)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @jrobble)

**Pull request merged**
