### PR TITLE
Update Docker component base image README files to mention pulling from Docker Hub

### PR DESCRIPTION
**Pull request by jrobble**
**Issues:**

- https://github.com/openmpf/openmpf/issues/1358

---
This change is [Reviewable](https://reviewable.io/reviews/openmpf/openmpf-docker/148)

### CODE REVIEW

**Review by clnowacki — CHANGES_REQUESTED** [review]
> Reviewed 5 of 5 files at r1.
> *[Reviewable](https://reviewable.io/reviews/openmpf/openmpf-docker/148)* status: all files reviewed, 6 unresolved discussions (waiting on @brosenberg42 and @jrobble)

___
*[README.md, line 158 at r1](https://reviewable.io/reviews/openmpf/openmpf-docker/148#-Mcssi3S52CvbNAA4cp4:-Mcssi3TAPurs35WdKYz:b-uztb2v) ([raw file](https://github.com/openmpf/openmpf-docker/blob/d61169349e42bffd08892322ae2e8644a9ba87b8/README.md#L158)):*
> ```Markdown
> ### Pull or Build the OpenMPF Docker Images
> 
> The simplest way to get started is to follow the steps in the "Quick Start" section of the documentation for the OpenMPF
> ```

Consider changing this to "The recommended way" instead of simplest, to make it stronger.
___
*[README.md, line 433 at r1](https://reviewable.io/reviews/openmpf/openmpf-docker/148#-Mct0GWeAo8PfGhSHiy2:-Mct0GWeAo8PfGhSHiy3:brsn40f) ([raw file](https://github.com/openmpf/openmpf-docker/blob/d61169349e42bffd08892322ae2e8644a9ba87b8/README.md#L433)):*
> ```Markdown
> 
> The Workflow Manager can be configured to trust additional certificate authorities. The Workflow Manager uses these
> certificates when it acts as an HTTPS client. For example, remote media download and job status callbacks.
> ```

The sentence starting with "For example" is a sentence fragment. You could change it to "Examples include remote media..."
___
*[README.md, line 495 at r1](https://reviewable.io/reviews/openmpf/openmpf-docker/148#-Mct0t6p9VggwXZpDX3K:-Mct0t6p9VggwXZpDX3L:b-rac8l0) ([raw file](https://github.com/openmpf/openmpf-docker/blob/d61169349e42bffd08892322ae2e8644a9ba87b8/README.md#L495)):*
> ```Markdown
> ### (Optional) Running Tests
> 
> Build the `openmpf_cpp_component_build`, `openmpf_cpp_executor`, and `openmpf_python_executor`
> ```

Is it possible to run the tests when the user has chosen to download images, as we recommended above, or do we not have an entry point for that in the prebuilt images?
___
*[SWARM.md, line 15 at r1](https://reviewable.io/reviews/openmpf/openmpf-docker/148#-Mct1g90COa67L-Ff2N-:-Mct1g90COa67L-Ff2N0:bz5rse6) ([raw file](https://github.com/openmpf/openmpf-docker/blob/d61169349e42bffd08892322ae2e8644a9ba87b8/SWARM.md#L15)):*
> ```Markdown
> 
> 1. A cluster of machines running the Docker daemon. The client and daemon
> (server) API must both be at least 1.24. Use the `docker version` command to check your client and daemon API versions.
> ```

"at least *version* 1.24."
___
*[SWARM.md, line 42 at r1](https://reviewable.io/reviews/openmpf/openmpf-docker/148#-Mct22cs1uJERwPOA72P:-Mct22cs1uJERwPOA72Q:bbmlrgi) ([raw file](https://github.com/openmpf/openmpf-docker/blob/d61169349e42bffd08892322ae2e8644a9ba87b8/SWARM.md#L42)):*
> ```Markdown
> ### Initialize the Swarm Cluster
> 
> Choose a machine that you wish to act as the manager node. You will be able to deploy and manager the stack from this
> ```

"deploy and *manage*"
___
*[SWARM.md, line 68 at r1](https://reviewable.io/reviews/openmpf/openmpf-docker/148#-Mct2JH_9sSo6Iw95K5C:-Mct2JH_9sSo6Iw95K5D:b-ahfnd5) ([raw file](https://github.com/openmpf/openmpf-docker/blob/d61169349e42bffd08892322ae2e8644a9ba87b8/SWARM.md#L68)):*
> ```Markdown
> section in the README.
> 
> In order to push the images to your own Docker registry, they each need to named with the approprate prefix for your
> ```

"they each need to *be* named..."
spelling of "appropriate"

**Review by brosenberg42 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/openmpf/openmpf-docker/148)* status: all files reviewed, 8 unresolved discussions (waiting on @jrobble)

___
*[README.md, line 56 at r1](https://reviewable.io/reviews/openmpf/openmpf-docker/148#-Mct45PL25sWg38k6amt:-Mct45PL25sWg38k6amu:b-i1l1st) ([raw file](https://github.com/openmpf/openmpf-docker/blob/d61169349e42bffd08892322ae2e8644a9ba87b8/README.md#L56)):*
> ```Markdown
> less but this is what we have been successful with), and 4096 MB (4 GB) of disk swap space.
> 
> #### Check the Linux Host Storage Driver
> ```

Can we get rid of this section or move it way down? I didn't have to do any of these things and it makes it hard to find the actual content. Most people can figure out how to install Docker on their own.
___
*[components/cpp_executor/README.md, line 60 at r1](https://reviewable.io/reviews/openmpf/openmpf-docker/148#-Mct5uWC9oho3goOS_rz:-Mct5uWC9oho3goOS_s-:b-w29o36) ([raw file](https://github.com/openmpf/openmpf-docker/blob/d61169349e42bffd08892322ae2e8644a9ba87b8/components/cpp_executor/README.md#L60)):*
> ```Markdown
> ```dockerfile
> # In first stage of the build we extend the openmpf_cpp_component_build base image.
> FROM openmpf_cpp_component_build:latest as build_component
> ```

Because of your changes above, this needs to be changed to `openmpf/openmpf_cpp_component_build`. Do not address this by adding `ARG BUILD_REGISTRY` as these are the minimal Dockerfile examples. The same change needs to be made for the Java and Python examples.

**Review by jrobble — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/openmpf/openmpf-docker/148)* status: 0 of 5 files reviewed, 8 unresolved discussions (waiting on @brosenberg42 and @clnowacki)

___
*[README.md, line 56 at r1](https://reviewable.io/reviews/openmpf/openmpf-docker/148#-Mct45PL25sWg38k6amt:-McucKkfAbFzbA5Jl8jf:b-896fix) ([raw file](https://github.com/openmpf/openmpf-docker/blob/d61169349e42bffd08892322ae2e8644a9ba87b8/README.md#L56)):*
<details><summary><i>Previously, brosenberg42 wrote…</i></summary><blockquote>

Can we get rid of this section or move it way down? I didn't have to do any of these things and it makes it hard to find the actual content. Most people can figure out how to install Docker on their own.
</blockquote></details>

Done.
___
*[README.md, line 158 at r1](https://reviewable.io/reviews/openmpf/openmpf-docker/148#-Mcssi3S52CvbNAA4cp4:-McucXa92k42hfKZW0Gt:b-896fix) ([raw file](https://github.com/openmpf/openmpf-docker/blob/d61169349e42bffd08892322ae2e8644a9ba87b8/README.md#L158)):*
<details><summary><i>Previously, clnowacki wrote…</i></summary><blockquote>

Consider changing this to "The recommended way" instead of simplest, to make it stronger.
</blockquote></details>

Done.
___
*[README.md, line 433 at r1](https://reviewable.io/reviews/openmpf/openmpf-docker/148#-Mct0GWeAo8PfGhSHiy2:-Mcucg7i7l7LM95otmHw:b-896fix) ([raw file](https://github.com/openmpf/openmpf-docker/blob/d61169349e42bffd08892322ae2e8644a9ba87b8/README.md#L433)):*
<details><summary><i>Previously, clnowacki wrote…</i></summary><blockquote>

The sentence starting with "For example" is a sentence fragment. You could change it to "Examples include remote media..."
</blockquote></details>

Done.
___
*[README.md, line 495 at r1](https://reviewable.io/reviews/openmpf/openmpf-docker/148#-Mct0t6p9VggwXZpDX3K:-Mcue9xs3bXuXK1YpNcf:bbz0mq9) ([raw file](https://github.com/openmpf/openmpf-docker/blob/d61169349e42bffd08892322ae2e8644a9ba87b8/README.md#L495)):*
<details><summary><i>Previously, clnowacki wrote…</i></summary><blockquote>

Is it possible to run the tests when the user has chosen to download images, as we recommended above, or do we not have an entry point for that in the prebuilt images?
</blockquote></details>

It's not possible because it requires them to build `openmpf_integration_tests`, which we don't push to Docker Hub. In general, I don't think anyone would want to run the tests unless they are building their own images. It's assumed that we ran the tests before pushing the images.
___
*[SWARM.md, line 15 at r1](https://reviewable.io/reviews/openmpf/openmpf-docker/148#-Mct1g90COa67L-Ff2N-:-Mcug6LZ-LPEUt4VJB8m:b-896fix) ([raw file](https://github.com/openmpf/openmpf-docker/blob/d61169349e42bffd08892322ae2e8644a9ba87b8/SWARM.md#L15)):*
<details><summary><i>Previously, clnowacki wrote…</i></summary><blockquote>

"at least *version* 1.24."
</blockquote></details>

Done.
___
*[SWARM.md, line 42 at r1](https://reviewable.io/reviews/openmpf/openmpf-docker/148#-Mct22cs1uJERwPOA72P:-McugBHQ0DtLdV2THFQ3:b-896fix) ([raw file](https://github.com/openmpf/openmpf-docker/blob/d61169349e42bffd08892322ae2e8644a9ba87b8/SWARM.md#L42)):*
<details><summary><i>Previously, clnowacki wrote…</i></summary><blockquote>

"deploy and *manage*"
</blockquote></details>

Done.
___
*[SWARM.md, line 68 at r1](https://reviewable.io/reviews/openmpf/openmpf-docker/148#-Mct2JH_9sSo6Iw95K5C:-McugSNS8by2a0TOqoR0:b-896fix) ([raw file](https://github.com/openmpf/openmpf-docker/blob/d61169349e42bffd08892322ae2e8644a9ba87b8/SWARM.md#L68)):*
<details><summary><i>Previously, clnowacki wrote…</i></summary><blockquote>

"they each need to *be* named..."
spelling of "appropriate"
</blockquote></details>

Done.
___
*[components/cpp_executor/README.md, line 60 at r1](https://reviewable.io/reviews/openmpf/openmpf-docker/148#-Mct5uWC9oho3goOS_rz:-McujEavAIaWUeTAf92m:bb0g73m) ([raw file](https://github.com/openmpf/openmpf-docker/blob/d61169349e42bffd08892322ae2e8644a9ba87b8/components/cpp_executor/README.md#L60)):*
<details><summary><i>Previously, brosenberg42 wrote…</i></summary><blockquote>

Because of your changes above, this needs to be changed to `openmpf/openmpf_cpp_component_build`. Do not address this by adding `ARG BUILD_REGISTRY` as these are the minimal Dockerfile examples. The same change needs to be made for the Java and Python examples.
</blockquote></details>

I think there are two options. If the user pulled the base images, then they would need to use the `openmpf/` prefix. If they built their own, then they don't need it. I described both options.

**Review by brosenberg42 — APPROVED** [review]
> Reviewed 5 of 5 files at r2.
> *[Reviewable](https://reviewable.io/reviews/openmpf/openmpf-docker/148)* status: all files reviewed, 6 unresolved discussions (waiting on @clnowacki)

**Review by clnowacki — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/openmpf/openmpf-docker/148)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @jrobble)

**Pull request merged**
