### PR TITLE
Build without bind mount

### PR DESCRIPTION
**Pull request by brosenberg42**
This change is [Reviewable](https://reviewable.io/reviews/openmpf/openmpf-docker/54)

### CODE REVIEW

**Comment by jrobble** [comment]
___
*[components/cpp_executor/Dockerfile, line 52 at r7](https://reviewable.io/reviews/openmpf/openmpf-docker/54#-LyaHnQwE2G83TjsN_wk:-Lyb1wG-BCcK2OXYjUnb:b-t1cgpp) ([raw file](https://github.com/openmpf/openmpf-docker/blob/009b5ba1bd63b7e0f31adb4f4d299e06f6f9bde6/components/cpp_executor/Dockerfile#L52)):*
<details><summary><i>Previously, jrobble (Jeff Robble) wrote…</i></summary><blockquote>

Is `--mount` valid here? I'm getting:

```
ERROR: for markup  Dockerfile parse error line 55: Unknown flag: mount
```

</blockquote></details>

If the build requires a certain version of Docker, or Docker to be configured in a certain way, please state so in the doc. Maybe I'm missing something.

**Comment by brosenberg42** [comment]
___
*[components/cpp_executor/Dockerfile, line 52 at r7](https://reviewable.io/reviews/openmpf/openmpf-docker/54#-LyaHnQwE2G83TjsN_wk:-LyiBvV3Dp-uq2_8J7Y-:batq64k) ([raw file](https://github.com/openmpf/openmpf-docker/blob/009b5ba1bd63b7e0f31adb4f4d299e06f6f9bde6/components/cpp_executor/Dockerfile#L52)):*
<details><summary><i>Previously, jrobble (Jeff Robble) wrote…</i></summary><blockquote>

Ok. I see the instructions for setting the env. vars in the `new-docker-setup.md` file you sent me; however, I believe you still need to update `README.md` in the openmpf-docker repo. You instruct the user to set `DOCKER_BUILDKIT=1` on a command-by-command basis. Also, I see no mention of `COMPOSE_DOCKER_CLI_BUILD=1` in that file, but I do see it used before running `docker-compose build ... --parallel` in the `Jenkinsfile`.
</blockquote></details>

You are right that it isn't mentioned in the README.md. That is because, as I mentioned above, I didn't intend to use the buildkit feature in the images built by docker-compose. I am still thinking about whether or not I want to remove the `RUN --mount` from the markup Dockerfile.

**Comment by jrobble** [comment]
___
*[components/cpp_executor/Dockerfile, line 52 at r7](https://reviewable.io/reviews/openmpf/openmpf-docker/54#-LyaHnQwE2G83TjsN_wk:-Lz8ENCb37L-UAxBioZ9:b-exj3dn) ([raw file](https://github.com/openmpf/openmpf-docker/blob/009b5ba1bd63b7e0f31adb4f4d299e06f6f9bde6/components/cpp_executor/Dockerfile#L52)):*
<details><summary><i>Previously, brosenberg42 wrote…</i></summary><blockquote>

When you use docker-compose with buildkit, it logs `Native build is an experimental feature and could change at any time`, so I would only want to use it if there was a good reason to. The non-buildkit way of doing it is pretty simple, so I don't think it justifies using it.
</blockquote></details>

Do we still want to use`syntax=docker/dockerfile:experimental` at the top of the markup Dockerfile?

**Comment by brosenberg42** [comment]
___
*[Jenkinsfile, line 408 at r3](https://reviewable.io/reviews/openmpf/openmpf-docker/54#-LyAWWvMCYvfD1x00A4j:-LzHtpK8DbaK9bFn4ccF:b-b97p3z) ([raw file](https://github.com/openmpf/openmpf-docker/blob/b76a6ba2e107abda7b012a1901bebeec54d818b5/Jenkinsfile#L408)):*
<details><summary><i>Previously, jrobble (Jeff Robble) wrote…</i></summary><blockquote>

Right, but I'm thinking about an optional way to override it.
</blockquote></details>

I am already concerned about the preserveContainersOnFailure option because I don't think people will properly clean up the containers.

**Comment by jrobble** [comment]
___
*[docker-compose.core.yml, line 72 at r10](https://reviewable.io/reviews/openmpf/openmpf-docker/54#-LzIqlf0C_NBVKI00G-a:-LzIqlf11oEd6iBQkO02:bj0tmkw) ([raw file](https://github.com/openmpf/openmpf-docker/blob/a902c09a2a448c13762dd86391f3b1b242ebf06d/docker-compose.core.yml#L72)):*
> ```YAML
>           - node.role == manager
> 
>   markup:
> ```

Note to self: Test that markup is independent of the WFM image.

**Comment by jrobble** [comment]
___
*[Jenkinsfile, line 302 at r3](https://reviewable.io/reviews/openmpf/openmpf-docker/54#-LyALP0J57kY1A-EAQWq:-LzNl30fDbJBW599CQig:b-an1055) ([raw file](https://github.com/openmpf/openmpf-docker/blob/b76a6ba2e107abda7b012a1901bebeec54d818b5/Jenkinsfile#L302)):*
<details><summary><i>Previously, jrobble (Jeff Robble) wrote…</i></summary><blockquote>

Note to self: Test this. Make sure SDK and openmpf-docker SHAs are added for component images.
</blockquote></details>

As discussed:

- Add the openmpf-docker SHA to the component images, not the base executor or build images. Actually, add it to all of the final OpenMPF images that are part of a deployment.
- Also, add the openmpf SHA to the component images and executor images, since the executor code is in the openmpf repo. I don't think the openmpf SHA needs to be added to the activemq image.

**Comment by jrobble** [comment]
___
*[README.md, line 259 at r10](https://reviewable.io/reviews/openmpf/openmpf-docker/54#-LzcEVUP6URLrT8KyreQ:-LzcEVUQ-EUYTnEvLpym:b-dpnqz4) ([raw file](https://github.com/openmpf/openmpf-docker/blob/a902c09a2a448c13762dd86391f3b1b242ebf06d/README.md#L259)):*
> ```Markdown
> Run the following command to create the new runtime images:
> 
> - `docker-compose build --parallel`
> ```

Any reason not to use `--progress plain` here? The output is more same, IMO, and will allow a user to better identify failures.

**Comment by jrobble** [comment]
___
*[README.md, line 259 at r10](https://reviewable.io/reviews/openmpf/openmpf-docker/54#-LzcEVUP6URLrT8KyreQ:-LzcFvwX4au7lAy0GM8E:bympi7i) ([raw file](https://github.com/openmpf/openmpf-docker/blob/a902c09a2a448c13762dd86391f3b1b242ebf06d/README.md#L259)):*
<details><summary><i>Previously, jrobble (Jeff Robble) wrote…</i></summary><blockquote>

Any reason not to use `--progress plain` here? The output is more same, IMO, and will allow a user to better identify failures. 
</blockquote></details>

Thinking about this more, I think that option is only available if using the build kit, which you don't really want to use for this command without a good reason. Personally, I think this is a good reason.

**Comment by jrobble** [comment]
___
*[README.md, line 259 at r10](https://reviewable.io/reviews/openmpf/openmpf-docker/54#-LzcEVUP6URLrT8KyreQ:-LzcGrND7N9PyVBLlocZ:b6r9q6t) ([raw file](https://github.com/openmpf/openmpf-docker/blob/a902c09a2a448c13762dd86391f3b1b242ebf06d/README.md#L259)):*
<details><summary><i>Previously, jrobble (Jeff Robble) wrote…</i></summary><blockquote>

Thinking about this more, I think that option is only available if using the build kit, which you don't really want to use for this command without a good reason. Personally, I think this is a good reason.
</blockquote></details>

* more sane

**Comment by jrobble** [comment]
___
*[openmpf_runtime/workflow-manager/docker-entrypoint.sh, line 86 at r11](https://reviewable.io/reviews/openmpf/openmpf-docker/54#-Lzhb5wt7-0ftCUiTHJz:-Lzhb5wt7-0ftCUiTHK-:bz6rycg) ([raw file](https://github.com/openmpf/openmpf-docker/blob/75752c525dae071a650779d4b97f99650e1cc124/openmpf_runtime/workflow-manager/docker-entrypoint.sh#L86)):*
> ```Shell
> 
> if [ ! -f "$markerFile" ]; then
>   mkdir -p "$MPF_HOME/share/config"
> ```

When deploying with config customizations, I'm getting:

 ```
[mpf@openmpf-master DOCKER]$ docker service logs --follow openmpf_workflow-manager
openmpf_workflow-manager.1.kg04q5s0ju7t@openmpf-master    | + rm --force '/opt/mpf/share/nodes/MPF_Channel/*-MPF-MasterNode.list'
openmpf_workflow-manager.1.kg04q5s0ju7t@openmpf-master    | + grep --quiet 'node_manager_id_*' /opt/mpf/share/data/nodeManagerConfig.xml
openmpf_workflow-manager.1.kg04q5s0ju7t@openmpf-master    | grep: /opt/mpf/share/data/nodeManagerConfig.xml: No such file or directory
openmpf_workflow-manager.1.kg04q5s0ju7t@openmpf-master    | + export JGROUPS_TCP_ADDRESS=83ede2651f26
openmpf_workflow-manager.1.kg04q5s0ju7t@openmpf-master    | + JGROUPS_TCP_ADDRESS=83ede2651f26
openmpf_workflow-manager.1.kg04q5s0ju7t@openmpf-master    | + '[' -f /scripts/docker-custom-entrypoint.sh ']'
openmpf_workflow-manager.1.kg04q5s0ju7t@openmpf-master    | + /scripts/docker-custom-entrypoint.sh
openmpf_workflow-manager.1.kg04q5s0ju7t@openmpf-master    | + markerFile=/opt/mpf/share/config/.docker-entrypoint-init
openmpf_workflow-manager.1.kg04q5s0ju7t@openmpf-master    | + '[' '!' -f /opt/mpf/share/config/.docker-entrypoint-init ']'
openmpf_workflow-manager.1.kg04q5s0ju7t@openmpf-master    | + mpfCustomPropertiesFile=/opt/mpf/share/config/mpf-custom.properties
openmpf_workflow-manager.1.kg04q5s0ju7t@openmpf-master    | + updateOrAddProperty /opt/mpf/share/config/mpf-custom.properties detection.segment.target.length 5000
openmpf_workflow-manager.1.kg04q5s0ju7t@openmpf-master    | + file=/opt/mpf/share/config/mpf-custom.properties
openmpf_workflow-manager.1.kg04q5s0ju7t@openmpf-master    | + key=detection.segment.target.length
openmpf_workflow-manager.1.kg04q5s0ju7t@openmpf-master    | + value=5000
openmpf_workflow-manager.1.kg04q5s0ju7t@openmpf-master    | + grep -q '^detection.segment.target.length=' /opt/mpf/share/config/mpf-custom.properties
openmpf_workflow-manager.1.kg04q5s0ju7t@openmpf-master    | grep: /opt/mpf/share/config/mpf-custom.properties: No such file or directory
openmpf_workflow-manager.1.kg04q5s0ju7t@openmpf-master    | + echo detection.segment.target.length=5000
openmpf_workflow-manager.1.kg04q5s0ju7t@openmpf-master    | /scripts/docker-custom-entrypoint.sh: line 44: /opt/mpf/share/config/mpf-custom.properties: No such file or directory
```

I believe this is because you removed this `mkdir -p "$MPF_HOME/share/config"` line.

I only got this after removing the `openmpf_shared_data` volume; forcing the deployment to repopulate the volume from scratch.

**Comment by jrobble** [comment]
___
*[openmpf_runtime/workflow-manager/docker-entrypoint.sh, line 86 at r11](https://reviewable.io/reviews/openmpf/openmpf-docker/54#-Lzhb5wt7-0ftCUiTHJz:-Lzhc2eKEV6AYcuaFLNm:b18a28y) ([raw file](https://github.com/openmpf/openmpf-docker/blob/75752c525dae071a650779d4b97f99650e1cc124/openmpf_runtime/workflow-manager/docker-entrypoint.sh#L86)):*
> I believe this is because you removed this mkdir -p "$MPF_HOME/share/config" line.

Actually, that and how you also removed the code that was creating `mpf-custom.properties` here. The custom config entrypoint expects that file to already exist. Maybe you want to move this code over there.

**Comment by jrobble** [comment]
___
*[Jenkinsfile, line 302 at r3](https://reviewable.io/reviews/openmpf/openmpf-docker/54#-LyALP0J57kY1A-EAQWq:-Lzn6r0JB6CH2nF_Gd1E:bfc64x2) ([raw file](https://github.com/openmpf/openmpf-docker/blob/b76a6ba2e107abda7b012a1901bebeec54d818b5/Jenkinsfile#L302)):*
<details><summary><i>Previously, jrobble (Jeff Robble) wrote…</i></summary><blockquote>

As discussed:

- Add the openmpf-docker SHA to the component images, not the base executor or build images. Actually, add it to all of the final OpenMPF images that are part of a deployment.
- Also, add the openmpf SHA to the component images and executor images, since the executor code is in the openmpf repo. I don't think the openmpf SHA needs to be added to the activemq image.

</blockquote></details>

Please add the openmpf SHA to the component executor images.

**Comment by jrobble** [comment]
___
*[Jenkinsfile, line 302 at r3](https://reviewable.io/reviews/openmpf/openmpf-docker/54#-LyALP0J57kY1A-EAQWq:-LzrF6EV8ttelWl3Hqmg:b4gvyil) ([raw file](https://github.com/openmpf/openmpf-docker/blob/b76a6ba2e107abda7b012a1901bebeec54d818b5/Jenkinsfile#L302)):*
<details><summary><i>Previously, jrobble (Jeff Robble) wrote…</i></summary><blockquote>

Please add the openmpf SHA to the component executor images.
</blockquote></details>

Actually, thinking about this more, we don't want to do this for the same reason we didn't want to add the openmpf-docker SHA. There is a lot of code in the openmpf repo that is not related the executor, and thus, we do not want to regenerate the executor images, and subsequently the component images, when that unrelated code changes.

**Comment by jrobble** [comment]
___
*[README.md, line 259 at r10](https://reviewable.io/reviews/openmpf/openmpf-docker/54#-LzcEVUP6URLrT8KyreQ:-LzsMFHCAfR5EVSxmnR0:b5uc6gg) ([raw file](https://github.com/openmpf/openmpf-docker/blob/a902c09a2a448c13762dd86391f3b1b242ebf06d/README.md#L259)):*
<details><summary><i>Previously, brosenberg42 wrote…</i></summary><blockquote>

I am just going to remove the `--parallel` argument for two reasons. One is that in general I want the README to be as simple as possible so we don't give the impression that you have to do all this complicated stuff to build the project. `DOCKER_BUILDKIT=1 COMPOSE_DOCKER_CLI_BUILD=1 docker-compose build --parallel` looks a lot scarier than `docker-compose build`. Having `--parallel` does violate this rule, so I shouldn't have added it to begin with. Secondly, marginally more readable output is not a good reason to use experimental features. Even with `--progress=plain`, the output is still interleaved. 
</blockquote></details>

I agree the command is simpler, but I don't think the "complicated" command you provided is all that complex either. The user is already specifying the `BUILD_KIT` variable when building the component base images. Personally, I feel that we should make the best use of what Docker has to offer. A user may see the "complex" command and think "These guys actually know what they're doing" because we're using new features in the right way.

I would say that the output without using `--progress=plain` is untraceable. The interleaved output itemizes the lines in such a way that you can figure out what's going on. I admit that it is a lot to look at, but at least you can work with it.

Making the build take longer by getting rid of parallelism doesn't seem like the best choice, but if you feel strongly about this then I'm fine with it. I haven't timed it or anything.

**Comment by jrobble** [comment]
___
*[SWARM.md, line 276 at r16](https://reviewable.io/reviews/openmpf/openmpf-docker/54#-M-zWWOd14P0pXyPadH4:-M-zWWOd14P0pXyPadH5:brzlkqb) ([raw file](https://github.com/openmpf/openmpf-docker/blob/168362654b2468ac710ef31387da9a01773b7485/SWARM.md#L276)):*
Change:

> The next time you deploy OpenMPF, all of the previous Node Manager logs will appear in the Logs web UI. To reduce clutter, consider running the following command to archive and remove the old Node Manager log files, where


to:

> The next time you deploy OpenMPF, all of the previous component container logs will appear in the Logs web UI. To reduce clutter, consider running the following command to archive and remove the old component log files, where

**Comment by jrobble** [comment]
___
*[SWARM.md, line 276 at r16](https://reviewable.io/reviews/openmpf/openmpf-docker/54#-M-zXlZZ7F7vC6CtdFtu:-M-zXlZZ7F7vC6CtdFtv:b6msk41) ([raw file](https://github.com/openmpf/openmpf-docker/blob/168362654b2468ac710ef31387da9a01773b7485/SWARM.md#L276)):*
> ```Markdown
> This preserves all of the Docker volumes.
> 
> The next time you deploy OpenMPF, all of the previous Node Manager logs will
> ```

Please update the `docker-swarm-logs.sh` script. There is a `--node-manager-logs` option that can be used to only archive/remove the node manager logs. We should instead support a `--component-logs` option that works similarly, but only works with the component logs (which you can easily find by looking for `_id_` in the log name.

**Comment by jrobble** [comment]
___
*[components/python_executor/Dockerfile, line 52 at r17](https://reviewable.io/reviews/openmpf/openmpf-docker/54#-M0P832S3BbLJpfRfUih:-M0P832S3BbLJpfRfUii:b2myzes) ([raw file](https://github.com/openmpf/openmpf-docker/blob/2ee284b455c8dd0b7c0234154728761c596ac709/components/python_executor/Dockerfile#L52)):*
I got this error:

> ImportError: No module named zipp

Please change this to:

```
    pip install --no-cache-dir --upgrade pip; \
    pip install --no-cache-dir --upgrade virtualenv; \
```

**Comment by jrobble** [comment]
___
*[SWARM.md, line 276 at r16](https://reviewable.io/reviews/openmpf/openmpf-docker/54#-M-zXlZZ7F7vC6CtdFtu:-M0TmNTZ2FlH3R_d_atM:b-4vp8dt) ([raw file](https://github.com/openmpf/openmpf-docker/blob/168362654b2468ac710ef31387da9a01773b7485/SWARM.md#L276)):*
<details><summary><i>Previously, jrobble (Jeff Robble) wrote…</i></summary><blockquote>

I think it's fine to just do all or nothing and not draw a separation between the component logs and other logs. In general, it's probably best to clean them all up as a set.
</blockquote></details>

This doesn't do what you would expect:

```
./scripts/docker-swarm-logs.sh -o tmp --rm
```

**Comment by jrobble** [comment]
___
*[SWARM.md, line 276 at r16](https://reviewable.io/reviews/openmpf/openmpf-docker/54#-M-zXlZZ7F7vC6CtdFtu:-M0UIfjlCCo4rXGP7pwW:bfbm03w) ([raw file](https://github.com/openmpf/openmpf-docker/blob/168362654b2468ac710ef31387da9a01773b7485/SWARM.md#L276)):*
<details><summary><i>Previously, brosenberg42 wrote…</i></summary><blockquote>

That's the behavior of the old script.
</blockquote></details>

If you did the following using the old script, it would actually remove the originals:

```
./scripts/docker-swarm-logs.sh --all-logs --archive tmp --remove-originals
```

This command silently ignores the `--rm` option and leaves the originals intact:

```
./scripts/docker-swarm-logs.sh -o tmp --rm
```

**Comment by jrobble** [comment]
___
*[scripts/docker-swarm-clean-shared-volume.sh, line 34 at r18](https://reviewable.io/reviews/openmpf/openmpf-docker/54#-M0UMC5E4q87dolvmBHk:-M0UMC5E4q87dolvmBHl:b-gq5qos) ([raw file](https://github.com/openmpf/openmpf-docker/blob/e30e42c35cb76ff4e6d6a8892ec43b2b15b5a1ca/scripts/docker-swarm-clean-shared-volume.sh#L34)):*
> ```Shell
>   echo "Usages:"
>   echo "docker-swarm-clean-shared-volume.sh [dir]"
>   exit 1
> ```

Please correct the -1 thing in the following files as well:

- docker-remove-images.sh
- docker-swarm-cleanup.sh
- docker-swarm-remove-images.sh
- docker-swarm-run-on-all-nodes.sh

**Pull request merged**
