### PR TITLE
Feat/wfm trigger

### PR DESCRIPTION
**Pull request by brosenberg42**
**Issues:**
- https://github.com/openmpf/openmpf/issues/1574

**Related PRs:**
- https://github.com/openmpf/openmpf/pull/1644
- https://github.com/openmpf/openmpf-components/pull/336
- https://github.com/openmpf/openmpf-contrib-components/pull/88
- https://github.com/openmpf/openmpf-cpp-component-sdk/pull/121
- https://github.com/openmpf/openmpf-python-component-sdk/pull/71
- https://github.com/openmpf/openmpf-java-component-sdk/pull/63

- - -
This change is [Reviewable](https://reviewable.io/reviews/openmpf/openmpf-docker/197)

### CODE REVIEW

**Review by jrobble — APPROVED** [review]
> Reviewed 5 of 5 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/openmpf/openmpf-docker/197)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @brosenberg42)

**Review by jrobble — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/openmpf/openmpf-docker/197)* status: all files reviewed, 1 unresolved discussion (waiting on @brosenberg42)

*[a discussion](https://reviewable.io/reviews/openmpf/openmpf-docker/197#-Nhl_bEi7bBW_7jq4KmF:-Nhl_bEi7bBW_7jq4KmG:b-5w565w) (no related file):*
Please update this text in the README:

```
# Takes the form: "<registry-host>:<registry-port>/<repository>/", where
# <repository> is usually "openmpf". Make sure to include the "/" at the end.
# Leave blank to use images on the local host or Docker Hub.
REGISTRY=
```

to:

```
# Takes the form: "<registry-host>:<registry-port>/<repository>/", where
# <repository> is usually "openmpf". Make sure to include the "/" at the end.
# Leave blank to use images on the local host.
# Use "openmpf/" to use images on Docker Hub.
REGISTRY=
```

___

**Review by brosenberg42 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/openmpf/openmpf-docker/197)* status: 5 of 6 files reviewed, 1 unresolved discussion (waiting on @brosenberg42 and @jrobble)

*[a discussion](https://reviewable.io/reviews/openmpf/openmpf-docker/197#-Nhl_bEi7bBW_7jq4KmF:-NiEj-YO324orwiu3yZX:b-896fix) (no related file):*
<details><summary><i>Previously, jrobble (Jeff Robble) wrote…</i></summary><blockquote>

Please update this text in the README:

```
# Takes the form: "<registry-host>:<registry-port>/<repository>/", where
# <repository> is usually "openmpf". Make sure to include the "/" at the end.
# Leave blank to use images on the local host or Docker Hub.
REGISTRY=
```

to:

```
# Takes the form: "<registry-host>:<registry-port>/<repository>/", where
# <repository> is usually "openmpf". Make sure to include the "/" at the end.
# Leave blank to use images on the local host.
# Use "openmpf/" to use images on Docker Hub.
REGISTRY=
```
</blockquote></details>

Done.

___

**Review by jrobble — APPROVED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/openmpf/openmpf-docker/197)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @brosenberg42)

**Pull request merged**
